Controllers/medicosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClinicaMVC.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using ClinicaMVC.Filtros;

namespace ClinicaMVC.Controllers
{
    [Authorize(Roles = "SuperAdmin, Administrador")]
    [FiltroAutorizacion]
    public class medicosController : Controller
    {
        private ProyectoVeris_MVC_Entities db = new ProyectoVeris_MVC_Entities();

        // GET: medicos
        public ActionResult Index()
        {
            var medicos = db.medicos.Include(m => m.AspNetUsers).Include(m => m.especialidades);
            return View(medicos.ToList());
        }

        // GET: medicos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            medicos medicos = db.medicos.Find(id);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            return View(medicos);
        }

        // GET: medicos/Create
        public ActionResult Create()
        {
            ViewBag.IdUsuario = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.IdEspecialidad = new SelectList(db.especialidades, "IdEspecialidad", "Descripcion");
            return View();
        }

        // POST: medicos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdMedico,Nombre,IdEspecialidad,IdUsuario,Foto")] medicos medicos)
        {
            if (ModelState.IsValid)
            {
                db.medicos.Add(medicos);
                db.SaveChanges();
                // Asignar el rol "Medico" al usuario
                var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                userManager.AddToRole(medicos.IdUsuario, "Medico");
                return RedirectToAction("Index");
            }

            ViewBag.IdUsuario = new SelectList(db.AspNetUsers, "Id", "Email", medicos.IdUsuario);
            ViewBag.IdEspecialidad = new SelectList(db.especialidades, "IdEspecialidad", "Descripcion", medicos.IdEspecialidad);
            return View(medicos);
        }

        // GET: medicos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            medicos medicos = db.medicos.Find(id);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdUsuario = new SelectList(db.AspNetUsers, "Id", "Email", medicos.IdUsuario);
            ViewBag.IdEspecialidad = new SelectList(db.especialidades, "IdEspecialidad", "Descripcion", medicos.IdEspecialidad);
            return View(medicos);
        }

        // POST: medicos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdMedico,Nombre,IdEspecialidad,IdUsuario,Foto")] medicos medicos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medicos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdUsuario = new SelectList(db.AspNetUsers, "Id", "Email", medicos.IdUsuario);
            ViewBag.IdEspecialidad = new SelectList(db.especialidades, "IdEspecialidad", "Descripcion", medicos.IdEspecialidad);
            return View(medicos);
        }

        // GET: medicos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            medicos medicos = db.medicos.Find(id);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            return View(medicos);
        }

        // POST: medicos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            medicos medicos = db.medicos.Find(id);
            db.medicos.Remove(medicos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
     body {
         background-image: url('@Url.Content("~/imagenes/recursos/fondo.png")');
         background-size: cover;
         background-position: center 2%;
         background-repeat: no-repeat;
         color: white;
     }
    </style>

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("PROYECTO VERIS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Administrador"))
                        {
                            <li>@Html.ActionLink("Especialidad", "Index", "Especialidades", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Medicamento", "Index", "Medicamentos", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Medico", "Index", "Medicos", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Paciente", "Index", "Pacientes", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Info Admin", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>


                        }
                        else if (User.IsInRole("Medico"))
                        {
                            <li>@Html.ActionLink("Consulta", "Index", "Consultas", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Receta", "Index", "Recetas", new { area = "" }, new { @class = "nav-link" })</li>
                        }
                        else if (User.IsInRole("SuperAdmin"))
                        {
                            <li>@Html.ActionLink("Consulta", "Index", "Consultas", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Especialidad", "Index", "Especialidades", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Medicamento", "Index", "Medicamentos", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Medico", "Index", "Medicos", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Paciente", "Index", "Pacientes", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Receta", "Index", "Recetas", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Roles", "Index", "AspNetRoles", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Usuarios", "Index", "AspNetUsers", new { area = "" }, new { @class = "nav-link" })</li>
                        }
                        else if (User.IsInRole("Paciente"))
                        {
                            <li>@Html.ActionLink("Consulta", "Index", "Consultas", new { area = "" }, new { @class = "nav-link" })</li>
                        }
                    }
                    else
                    {
                        <li>@Html.ActionLink("Medico", "Index", "medicos", new { area = "" }, new { @class = "nav-link", id = "actionLink1" })</li>
                        <li>@Html.ActionLink("Paciente", "Index", "pacientes", new { area = "" }, new { @class = "nav-link", id = "actionLink2" })</li>
                        <li>@Html.ActionLink("Administrador", "Index", "pacientes", new { area = "" }, new { @class = "nav-link", id = "mostrarVistaParcial" })</li>

                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>